### ISSUE TITLE
Example does not match implementation

### ISSUE THREAD

**Issue by thgh** [dzek69/html-safe-json#2]
https://github.com/dzek69/html-safe-json/blob/e2d21972a6d0100ae3f970b4abe428faeadb2ee4/src/index.js#L26

According to the code I don't expect the output to include `\u002f`

**Comment by dzek69** [comment]
Thanks for pointing that out.

This code were extracted from another project and I've changed implementation a little bit, it's all unit tested but I left the example as it was by accident.

master and npm are now updated with version with corrected jsdoc

Thank you again 👍
